## drive encryption
aesni_load=YES
geom_eli_load=YES
kern.geom.label.disk_ident.enable=0
kern.geom.label.gptid.enable=0
cryptodev_load=YES

## boot
autoboot_delay=2
boot_mute=YES
beastie_disable=NO

## kernel
security.bsd.allow_destructive_dtrace=0
hw.usb.no_boot_wait=1
hw.psm.synaptics_support=1
hw.psm.elantech_support=1

## modules
zfs_load=YES
ahci_load=YES
acpi_asus_wmi_load=YES
vboxdrv_load=YES

## colors:
# black
kern.vt.color.0.rgb="#202226" # bg
kern.vt.color.8.rgb="#8486a4"
# red
kern.vt.color.1.rgb="#8e84a4"
kern.vt.color.9.rgb="#b8a8c0"
# green
kern.vt.color.2.rgb="#9aa8b9"
kern.vt.color.10.rgb="#c1d1df"
# yellow
kern.vt.color.3.rgb="#8c8ea6"
kern.vt.color.11.rgb="#d9e1ec"
# blue
kern.vt.color.4.rgb="#9496b4"
kern.vt.color.12.rgb="#8486a4"
# magenta
kern.vt.color.5.rgb="#b9a8c0"
kern.vt.color.13.rgb="#9d84a4"
# cyan
kern.vt.color.6.rgb="#b4b6d4"
kern.vt.color.14.rgb="#c8c8ee"
# white
kern.vt.color.7.rgb="#b8c8ee"
kern.vt.color.15.rgb="#dcd6e4" # fg
