# all the flags here were breaking virtualbox, llvm14 and my kernel.

MAKEOPTS+=-j12
KERNCONF=BSD LATEX-HK
OPTIMIZED_CFLAGS=YES
BUILD_OPTIMIZED=YES
WITH_CPUFLAGS=YES
OPTIONS_SET+=OPTIMIZED_CFLAGS CPUFLAGS
WITHOUT_DEBUG=YES
NO_INET6=YES

# awful awful awful LAWFUL!!!
OPTIONS_UNSET+=DEBUG
OPTIONS_UNSET+=PULSEAUDIO
OPTIONS_UNSET+=ALSA
OPTIONS_SET+=DOCS
OPTIONS_SET+=NLS
OPTIONS_SET+=X11
