# system
zfs_enable=YES
dumpdev=AUTO # AUTO - crash dumps enabled. NO - disabled.
kld_list="amdgpu acpi_video fusefs"
allscreens_flags="-f spleen-8x16"
syslogd_flags="-ss"
keyrate="250.34"
## daemons
moused_nondefault_enable=YES
sshd_enable=NO
local_unbound_enable=NO
powerd_enable=YES
dbus_enable=YES
rc_startmsgs=NO
ntpd_enable=YES
ntpdate_enable=YES
clear_tmp_enable=YES

# virt/bhyve
#vm_enable=YES
#vm_dir="zfs:texlive/stuff/virt"
#vm_list=""
#vm_delay=3

# virt/virtualbox
vboxnet_enable="YES"
devfs_system_ruleset="system"

# net
hostname="warm-lap"
gateway_enable=YES
defaultroute_delay=0
## net/wireless
wlans_rtwn0="wadapt"
ifconfig_wadapt="WPA DHCP"
archlinux_enable="YES"
moused_enable="NO"
lightdm_enable="NO"
