# these were the flags i was using
#HK_OPT=-O2 -pipe -mtune=native
#HK_CFLAG=-fno-strict-aliasing -fno-fast-math -fno-lto -fomit-frame-pointer -momit-leaf-frame-pointer
# don't just uncomment this for some ungodly reason, if you want to use them (and break everything) then add CFLAGS, CXXFLAGS and COPTFLAGS
MAKEOPTS+=-j12
KERNCONF=BSD LATEX-HK
#OPTIMIZED_CFLAGS=YES
BUILD_OPTIMIZED=YES
WITH_CPUFLAGS=YES
OPTIONS_SET+=OPTIMIZED_CFLAGS CPUFLAGS
WITHOUT_DEBUG=YES
CPUTYPE?=native
