#!/bin/sh

if echo $1 | grep -q del; then
scrot -s -f -l style=solid,color=#dbb0ba,width=2 ~/adrod/img.png -e 'xclip -selection clipboard -target image/png -i $f ; rm $f'
elif echo $1 | grep -q 0x0; then
scrot -s -f -l style=solid,color=#dbb0ba,width=2 ~/adrod/img.png -e 'xclip -selection clipboard -target image/png -i $f ; echo $f > /tmp/0x0'
f=$(cat "/tmp/0x0")
cat $f | curl -F "file=@-" https://0x0.st > /tmp/0x0link
cat /tmp/0x0link | xmessage -title "0x0.st link" -file - &
cat /tmp/0x0link | xclip -selection clipboard
rm /tmp/0x0link
rm $f
else
scrot -s -f -l style=solid,color=#abb0ba,width=2 ~/adrod/img.png -e 'xclip -selection clipboard -target image/png -i $f'
fi
