autoboot_delay=2
boot_mute=NO

kern.geom.label.disk_ident.enable=1
kern.geom.label.gptid.enable=1
security.bsd.allow_destructive_dtrace=0
hw.usb.no_boot_wait=1
hw.psm.elantech_support=1
ahci_load=YES
zfs_load=YES
zfs_enable=YES
vfs.root.mountfrom="zfs:plan/ROOT/bsd"
cuse_load=YES

vm.kmem_size="330M"
vm.kmem_size_max="330M"
vfs.zfs.arc_max="40M"
vfs.zfs.vdev.cache.size="5M"
vfs.zfs.prefetch_disable=1
vfs.zfs.txg.timeout=3
kern.maxvnodes=200000
vfs.zfs.write_limit_override=1073741824

kern.vt.color.0.rgb="#f5eeeb"
kern.vt.color.8.rgb="#7e705a"
kern.vt.color.1.rgb="#cb6077"
kern.vt.color.9.rgb="#cb6077"
kern.vt.color.2.rgb="#beb55b"
kern.vt.color.10.rgb="#beb55b"
kern.vt.color.3.rgb="#f4bc87"
kern.vt.color.11.rgb="#f4bc87"
kern.vt.color.4.rgb="#8ab3b5"
kern.vt.color.12.rgb="#8ab3b5"
kern.vt.color.5.rgb="#a89bb9"
kern.vt.color.13.rgb="#a89bb9"
kern.vt.color.6.rgb="#7bbda4"
kern.vt.color.14.rgb="#7bbda4"
kern.vt.color.7.rgb="#645240"
kern.vt.color.15.rgb="#64A240"
