hostname=jellybeans
gateway_enable=YES
defaultroute_delay=0

moused_enable=YES
powerd_enable=YES
rc_startmsgs=NO
# ntpd_enable=YES
# ntpdate_enable=YES
clear_tmp_enable=YES

kld_list="i915kms acpi_video fusefs"
allscreens_flags="-f vgarom-8x16"
syslogd_flags="-ss"
keyrate="250.34"

wlans_ath0=owo
ifconfig_owo="WPA DHCP"

# keymap=ru.koi8-r
# scrnmap=koi8-r2cp866
# font8x16=cp866b-8x16
# font8x14=cp866-8x14
# font8x8=cp866-8x8
# mousechar_start=3
seatd_enable="NO"
dbus_enable="YES"
