security.bsd.allow_destructive_dtrace=0
kern.geom.label.disk_ident.enable="0"
kern.geom.label.gptid.enable="0"
cryptodev_load="YES"
zfs_load="YES"
hw.usb.no_boot_wait=1 

boot_mute="NO"
autoboot_delay="1"
beastie_disable="NO"
ahci_load="YES"
#vmm_load="YES"
if_bridge_load="YES"
if_tap_load="YES"
vboxdrv_load="YES"
cuse_load="YES"

# black
kern.vt.color.0.rgb="#282b30"
kern.vt.color.8.rgb="#868d95"
# red
kern.vt.color.1.rgb="#f8c8ee"
kern.vt.color.9.rgb="#f4b6d4"
# green
kern.vt.color.2.rgb="#c4b6d4"
kern.vt.color.10.rgb="#d8c8ee"
# yellow
kern.vt.color.3.rgb="#9486a4"
kern.vt.color.11.rgb="#d8c8ee"
# blue
kern.vt.color.4.rgb="#d8c8ee"
kern.vt.color.12.rgb="#d8c8ee"
# magenta
kern.vt.color.5.rgb="#a496b4"
kern.vt.color.13.rgb="#d8c8ee"
# cyan
kern.vt.color.6.rgb="#c4b6d4"
kern.vt.color.14.rgb="#d8c8ee"
# white
kern.vt.color.7.rgb="#bec2da"
kern.vt.color.15.rgb="#ffffff"
