## safe cflags
CFLAGS+=-O2 -pipe -fno-strict-aliasing -mtune=native -march=native -fno-lto
COPTFLAGS+=-O2 -pipe -fno-strict-aliasing -mtune=native -march=native -fno-lto
CXXFLAGS+=-O2 -pipe -fno-strict-aliasing -mtune=native -march=native -fno-lto

MAKEOPTS+=-j12
KERNCONF=BSD MUZKERN
OPTIMIZED_CFLAGS=YES
BUILD_OPTIMIZED=YES
WITH_CPUFLAGS=YES
OPTIONS_SET+=OPTIMIZED_CFLAGS CPUFLAGS
WITHOUT_DEBUG=YES
NO_INET6=YES

CC=clang
CXX=clang++
CPP=clang-cpp
NM=/usr/bin/llvm-nm
AR=/usr/bin/llvm-ar
ARFLAGS=cr
RANLIB=/usr/bin/llvm-ranlib
RANLIBFLAGS=
