allscreens_flags="-f vgarom-8x16"
clear_tmp_enable="YES"
blued_enable="YES"
syslogd_flags="-ss"
hostname="VideoLan"
wlans_iwm0="wlan0"
ifconfig_wlan0="WPA DHCP"
local_unbound_enable="YES"
sshd_enable="NO"
ntpd_enable="YES"
ntpd_sync_on_start="YES"
powerd_enable="YES"
moused_nondefault_enable="NO"
# Set dumpdev to "AUTO" to e'nable crash dumps, "NO" to disable
dumpdev="AUTO"
zfs_enable="YES"
kld_list="amdgpu /boot/modules/ng_hci.ko fusefs"
moused_ums1_enable="YES"
moused_flags="-F 500"
# lightdm_enable="NO"
dbus_enable="YES"
# seatd_enable="YES"
keyrate="250.34"
archlinux_enable="YES"
defaultroute_delay="0"
# sndiod_enable="YES"

vboxnet_enable="YES"
devfs_system_ruleset="system"

# 9front bhyve

#if_bridge_load="YES"
#if_tap_load="YES"
#cloned_interfaces="bridge0 tap0"
#ifconfig_bridge0="DHCP addm ue0 addm tap0"
#ifconfig_bridge0_alias0="inet 10.0.0.1/24"
#ifconfig_re0="DHCP"
#ifconfig_ue0="DHCP"
#wlans_rtwn0="wlan1"
#ifconfig_wlan1="WPA DHCP"
